"""Integration tests for the 'add' command."""

import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]

COMBINATIONS = [
    ("ddd", "sqlalchemy"),
    ("ddd", "tortoise"),
    ("mvc", "sqlalchemy"),
    ("mvc", "tortoise"),
]


def run_cli_create(destination: Path, design: str, orm: str) -> None:
    """Create a new project using the CLI."""
    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT / "src")
    subprocess.run(
        [
            sys.executable,
            "-m",
            "cli",
            "create",
            "test-app",
            "--orm",
            orm,
            "--design",
            design,
            str(destination),
        ],
        check=True,
        env=env,
    )


def run_cli_add(project_path: Path, name: str) -> None:
    """Add business logic to an existing project using the CLI."""
    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT / "src")
    subprocess.run(
        [
            sys.executable,
            "-m",
            "cli",
            "add",
            name,
            "-p",
            str(project_path),
        ],
        check=True,
        env=env,
    )


def run_make_migration(project_path: Path) -> subprocess.CompletedProcess:
    """Run make makemigration in the project directory."""
    env = os.environ.copy()
    return subprocess.run(
        ["make", "makemigration", "MIGRATION_MESSAGE=add_product"],
        cwd=project_path,
        capture_output=True,
        text=True,
        env=env,
    )




@pytest.mark.integration
@pytest.mark.parametrize("design,orm", COMBINATIONS)
def test_add_command_creates_files(tmp_path: Path, design: str, orm: str) -> None:
    """Test that the add command creates all expected files."""
    project_dir = tmp_path / "test-project"
    run_cli_create(project_dir, design=design, orm=orm)
    
    # Add a new business logic module
    run_cli_add(project_dir, "product")
    
    if design == "ddd":
        # Check DDD files were created
        assert (project_dir / "src" / "app" / "domain" / "product" / "__init__.py").exists()
        assert (project_dir / "src" / "app" / "domain" / "product" / "entities.py").exists()
        assert (project_dir / "src" / "app" / "domain" / "product" / "repository.py").exists()
        assert (project_dir / "src" / "app" / "infrastructure" / "database" / "repository" / "product.py").exists()
        assert (project_dir / "src" / "app" / "operational" / "product.py").exists()
        assert (project_dir / "src" / "app" / "presentation" / "product" / "__init__.py").exists()
        assert (project_dir / "src" / "app" / "presentation" / "product" / "contracts.py").exists()
        assert (project_dir / "src" / "app" / "presentation" / "product" / "rest.py").exists()
        
        # Check table was added
        tables_content = (project_dir / "src" / "app" / "infrastructure" / "database" / "tables.py").read_text()
        assert "ProductTable" in tables_content
        
        # Check domain import was updated
        domain_init = (project_dir / "src" / "app" / "domain" / "__init__.py").read_text()
        assert "product" in domain_init
        
        # Check routes were registered
        pres_init = (project_dir / "src" / "app" / "presentation" / "__init__.py").read_text()
        assert "product" in pres_init
        assert "product.register(app)" in pres_init
        
    elif design == "mvc":
        # Check MVC files were appended
        models_content = (project_dir / "src" / "app" / "models" / "models.py").read_text()
        assert "ProductTable" in models_content
        
        repo_content = (project_dir / "src" / "app" / "models" / "repository.py").read_text()
        assert "ProductRepository" in repo_content
        
        assert (project_dir / "src" / "app" / "views" / "product.py").exists()
        
        # Check routes were registered in urls.py
        urls_content = (project_dir / "src" / "app" / "urls.py").read_text()
        assert "product" in urls_content
        assert "product.register(app)" in urls_content


@pytest.mark.integration
@pytest.mark.parametrize("design,orm", COMBINATIONS)
def test_add_command_no_lint_errors(tmp_path: Path, design: str, orm: str) -> None:
    """Test that the generated code from add command passes ruff linting."""
    project_dir = tmp_path / "test-project-lint"
    run_cli_create(project_dir, design=design, orm=orm)
    run_cli_add(project_dir, "product")
    
    # Check only the files generated by add command
    if design == "ddd":
        files_to_check = [
            project_dir / "src" / "app" / "domain" / "product",
            project_dir / "src" / "app" / "infrastructure" / "database" / "repository" / "product.py",
            project_dir / "src" / "app" / "operational" / "product.py",
            project_dir / "src" / "app" / "presentation" / "product",
        ]
    else:  # mvc
        files_to_check = [
            project_dir / "src" / "app" / "models" / "models.py",
            project_dir / "src" / "app" / "models" / "repository.py",
            project_dir / "src" / "app" / "views" / "product.py",
        ]
    
    for file_path in files_to_check:
        if file_path.exists():
            result = subprocess.run(
                ["ruff", "check", str(file_path)],
                capture_output=True,
                text=True,
            )
            assert result.returncode == 0, f"Ruff check failed for {file_path}:\n{result.stdout}\n{result.stderr}"


@pytest.mark.integration
@pytest.mark.parametrize("design,orm", COMBINATIONS)
def test_add_command_multiple_entities(tmp_path: Path, design: str, orm: str) -> None:
    """Test adding multiple business logic entities."""
    project_dir = tmp_path / "test-project-multi"
    run_cli_create(project_dir, design=design, orm=orm)
    
    # Add multiple entities
    run_cli_add(project_dir, "product")
    run_cli_add(project_dir, "order")
    run_cli_add(project_dir, "category")
    
    if design == "ddd":
        # Check all entities exist
        for entity in ["product", "order", "category"]:
            assert (project_dir / "src" / "app" / "domain" / entity / "__init__.py").exists()
            assert (project_dir / "src" / "app" / "presentation" / entity / "__init__.py").exists()
        
        # Check all are in domain __init__
        domain_init = (project_dir / "src" / "app" / "domain" / "__init__.py").read_text()
        assert "product" in domain_init
        assert "order" in domain_init
        assert "category" in domain_init
        
    elif design == "mvc":
        models_content = (project_dir / "src" / "app" / "models" / "models.py").read_text()
        repo_content = (project_dir / "src" / "app" / "models" / "repository.py").read_text()
        
        for entity in ["product", "order", "category"]:
            name = "".join(word.capitalize() for word in entity.split("_"))
            assert f"{name}Table" in models_content
            assert f"{name}Repository" in repo_content
            assert (project_dir / "src" / "app" / "views" / f"{entity}.py").exists()


@pytest.mark.integration
def test_add_command_fails_without_robyn_config(tmp_path: Path) -> None:
    """Test that add command fails if pyproject.toml doesn't have robyn-config section."""
    project_dir = tmp_path / "non-robyn-project"
    project_dir.mkdir()
    
    # Create a minimal pyproject.toml without robyn-config
    pyproject = project_dir / "pyproject.toml"
    pyproject.write_text('[project]\nname = "test"\nversion = "0.1.0"\n')
    
    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT / "src")
    
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "cli",
            "add",
            "product",
            "-p",
            str(project_dir),
        ],
        capture_output=True,
        text=True,
        env=env,
    )
    
    assert result.returncode != 0
    assert "robyn-config" in result.stdout.lower() or "robyn-config" in result.stderr.lower()


@pytest.mark.integration
def test_add_command_fails_without_pyproject(tmp_path: Path) -> None:
    """Test that add command fails if pyproject.toml doesn't exist."""
    project_dir = tmp_path / "empty-project"
    project_dir.mkdir()
    
    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT / "src")
    
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "cli",
            "add",
            "product",
            "-p",
            str(project_dir),
        ],
        capture_output=True,
        text=True,
        env=env,
    )
    
    assert result.returncode != 0
    assert "pyproject.toml" in result.stdout or "pyproject.toml" in result.stderr
